// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wikipage.proto

public final class Wikipage {
  private Wikipage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rcdn.Page)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     */
    String getTitle();
    /**
     * <code>required string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required string url = 3;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 3;</code>
     */
    String getUrl();
    /**
     * <code>required string url = 3;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>required int32 page_id = 4;</code>
     */
    boolean hasPageId();
    /**
     * <code>required int32 page_id = 4;</code>
     */
    int getPageId();

    /**
     * <code>required int32 revision_id = 5;</code>
     */
    boolean hasRevisionId();
    /**
     * <code>required int32 revision_id = 5;</code>
     */
    int getRevisionId();

    /**
     * <code>required string content = 6;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 6;</code>
     */
    String getContent();
    /**
     * <code>required string content = 6;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required string summary = 7;</code>
     */
    boolean hasSummary();
    /**
     * <code>required string summary = 7;</code>
     */
    String getSummary();
    /**
     * <code>required string summary = 7;</code>
     */
    com.google.protobuf.ByteString
        getSummaryBytes();

    /**
     * <code>optional string html = 8;</code>
     */
    boolean hasHtml();
    /**
     * <code>optional string html = 8;</code>
     */
    String getHtml();
    /**
     * <code>optional string html = 8;</code>
     */
    com.google.protobuf.ByteString
        getHtmlBytes();

    /**
     * <code>optional string category = 9;</code>
     */
    boolean hasCategory();
    /**
     * <code>optional string category = 9;</code>
     */
    String getCategory();
    /**
     * <code>optional string category = 9;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    java.util.List<rcdn.Wikipage.Page.Image> 
        getImageList();
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    rcdn.Wikipage.Page.Image getImage(int index);
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    int getImageCount();
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    java.util.List<? extends rcdn.Wikipage.Page.ImageOrBuilder> 
        getImageOrBuilderList();
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    rcdn.Wikipage.Page.ImageOrBuilder getImageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code rcdn.Page}
   */
  public static final class Page extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rcdn.Page)
      PageOrBuilder {
    // Use Page.newBuilder() to construct.
    private Page(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Page(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Page defaultInstance;
    public static Page getDefaultInstance() {
      return defaultInstance;
    }

    public Page getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Page(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              url_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pageId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              revisionId_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              content_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              summary_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              html_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              category_ = bs;
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                image_ = new java.util.ArrayList<rcdn.Wikipage.Page.Image>();
                mutable_bitField0_ |= 0x00000200;
              }
              image_.add(input.readMessage(rcdn.Wikipage.Page.Image.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          image_ = java.util.Collections.unmodifiableList(image_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rcdn.Wikipage.internal_static_rcdn_Page_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rcdn.Wikipage.internal_static_rcdn_Page_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rcdn.Wikipage.Page.class, rcdn.Wikipage.Page.Builder.class);
    }

    public static com.google.protobuf.Parser<Page> PARSER =
        new com.google.protobuf.AbstractParser<Page>() {
      public Page parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Page(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Page> getParserForType() {
      return PARSER;
    }

    public interface ImageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rcdn.Page.Image)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string link = 1;</code>
       */
      boolean hasLink();
      /**
       * <code>required string link = 1;</code>
       */
      String getLink();
      /**
       * <code>required string link = 1;</code>
       */
      com.google.protobuf.ByteString
          getLinkBytes();
    }
    /**
     * Protobuf type {@code rcdn.Page.Image}
     */
    public static final class Image extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:rcdn.Page.Image)
        ImageOrBuilder {
      // Use Image.newBuilder() to construct.
      private Image(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Image(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Image defaultInstance;
      public static Image getDefaultInstance() {
        return defaultInstance;
      }

      public Image getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Image(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                link_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rcdn.Wikipage.internal_static_rcdn_Page_Image_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rcdn.Wikipage.internal_static_rcdn_Page_Image_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rcdn.Wikipage.Page.Image.class, rcdn.Wikipage.Page.Image.Builder.class);
      }

      public static com.google.protobuf.Parser<Image> PARSER =
          new com.google.protobuf.AbstractParser<Image>() {
        public Image parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Image(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Image> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int LINK_FIELD_NUMBER = 1;
      private Object link_;
      /**
       * <code>required string link = 1;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string link = 1;</code>
       */
      public String getLink() {
        Object ref = link_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            link_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string link = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        link_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasLink()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getLinkBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getLinkBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static rcdn.Wikipage.Page.Image parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static rcdn.Wikipage.Page.Image parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static rcdn.Wikipage.Page.Image parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static rcdn.Wikipage.Page.Image parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(rcdn.Wikipage.Page.Image prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code rcdn.Page.Image}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:rcdn.Page.Image)
          rcdn.Wikipage.Page.ImageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return rcdn.Wikipage.internal_static_rcdn_Page_Image_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return rcdn.Wikipage.internal_static_rcdn_Page_Image_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  rcdn.Wikipage.Page.Image.class, rcdn.Wikipage.Page.Image.Builder.class);
        }

        // Construct using rcdn.Wikipage.Page.Image.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          link_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return rcdn.Wikipage.internal_static_rcdn_Page_Image_descriptor;
        }

        public rcdn.Wikipage.Page.Image getDefaultInstanceForType() {
          return rcdn.Wikipage.Page.Image.getDefaultInstance();
        }

        public rcdn.Wikipage.Page.Image build() {
          rcdn.Wikipage.Page.Image result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public rcdn.Wikipage.Page.Image buildPartial() {
          rcdn.Wikipage.Page.Image result = new rcdn.Wikipage.Page.Image(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.link_ = link_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof rcdn.Wikipage.Page.Image) {
            return mergeFrom((rcdn.Wikipage.Page.Image)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(rcdn.Wikipage.Page.Image other) {
          if (other == rcdn.Wikipage.Page.Image.getDefaultInstance()) return this;
          if (other.hasLink()) {
            bitField0_ |= 0x00000001;
            link_ = other.link_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasLink()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          rcdn.Wikipage.Page.Image parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (rcdn.Wikipage.Page.Image) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private Object link_ = "";
        /**
         * <code>required string link = 1;</code>
         */
        public boolean hasLink() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string link = 1;</code>
         */
        public String getLink() {
          Object ref = link_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              link_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string link = 1;</code>
         */
        public com.google.protobuf.ByteString
            getLinkBytes() {
          Object ref = link_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            link_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string link = 1;</code>
         */
        public Builder setLink(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          link_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string link = 1;</code>
         */
        public Builder clearLink() {
          bitField0_ = (bitField0_ & ~0x00000001);
          link_ = getDefaultInstance().getLink();
          onChanged();
          return this;
        }
        /**
         * <code>required string link = 1;</code>
         */
        public Builder setLinkBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          link_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:rcdn.Page.Image)
      }

      static {
        defaultInstance = new Image(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:rcdn.Page.Image)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private Object title_;
    /**
     * <code>required string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string title = 2;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 3;
    private Object url_;
    /**
     * <code>required string url = 3;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string url = 3;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_ID_FIELD_NUMBER = 4;
    private int pageId_;
    /**
     * <code>required int32 page_id = 4;</code>
     */
    public boolean hasPageId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 page_id = 4;</code>
     */
    public int getPageId() {
      return pageId_;
    }

    public static final int REVISION_ID_FIELD_NUMBER = 5;
    private int revisionId_;
    /**
     * <code>required int32 revision_id = 5;</code>
     */
    public boolean hasRevisionId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 revision_id = 5;</code>
     */
    public int getRevisionId() {
      return revisionId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private Object content_;
    /**
     * <code>required string content = 6;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string content = 6;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUMMARY_FIELD_NUMBER = 7;
    private Object summary_;
    /**
     * <code>required string summary = 7;</code>
     */
    public boolean hasSummary() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string summary = 7;</code>
     */
    public String getSummary() {
      Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          summary_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string summary = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTML_FIELD_NUMBER = 8;
    private Object html_;
    /**
     * <code>optional string html = 8;</code>
     */
    public boolean hasHtml() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string html = 8;</code>
     */
    public String getHtml() {
      Object ref = html_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          html_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string html = 8;</code>
     */
    public com.google.protobuf.ByteString
        getHtmlBytes() {
      Object ref = html_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        html_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 9;
    private Object category_;
    /**
     * <code>optional string category = 9;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string category = 9;</code>
     */
    public String getCategory() {
      Object ref = category_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string category = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_FIELD_NUMBER = 10;
    private java.util.List<rcdn.Wikipage.Page.Image> image_;
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    public java.util.List<rcdn.Wikipage.Page.Image> getImageList() {
      return image_;
    }
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    public java.util.List<? extends rcdn.Wikipage.Page.ImageOrBuilder> 
        getImageOrBuilderList() {
      return image_;
    }
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    public int getImageCount() {
      return image_.size();
    }
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    public rcdn.Wikipage.Page.Image getImage(int index) {
      return image_.get(index);
    }
    /**
     * <code>repeated .rcdn.Page.Image image = 10;</code>
     */
    public rcdn.Wikipage.Page.ImageOrBuilder getImageOrBuilder(
        int index) {
      return image_.get(index);
    }

    private void initFields() {
      id_ = 0;
      title_ = "";
      url_ = "";
      pageId_ = 0;
      revisionId_ = 0;
      content_ = "";
      summary_ = "";
      html_ = "";
      category_ = "";
      image_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRevisionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSummary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getImageCount(); i++) {
        if (!getImage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pageId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, revisionId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getContentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSummaryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getHtmlBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCategoryBytes());
      }
      for (int i = 0; i < image_.size(); i++) {
        output.writeMessage(10, image_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pageId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, revisionId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSummaryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getHtmlBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getCategoryBytes());
      }
      for (int i = 0; i < image_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, image_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rcdn.Wikipage.Page parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rcdn.Wikipage.Page parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rcdn.Wikipage.Page parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rcdn.Wikipage.Page parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rcdn.Wikipage.Page parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rcdn.Wikipage.Page parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rcdn.Wikipage.Page parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rcdn.Wikipage.Page parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rcdn.Wikipage.Page parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rcdn.Wikipage.Page parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rcdn.Wikipage.Page prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rcdn.Page}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rcdn.Page)
        rcdn.Wikipage.PageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rcdn.Wikipage.internal_static_rcdn_Page_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rcdn.Wikipage.internal_static_rcdn_Page_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rcdn.Wikipage.Page.class, rcdn.Wikipage.Page.Builder.class);
      }

      // Construct using rcdn.Wikipage.Page.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getImageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        revisionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        summary_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        html_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        if (imageBuilder_ == null) {
          image_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          imageBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rcdn.Wikipage.internal_static_rcdn_Page_descriptor;
      }

      public rcdn.Wikipage.Page getDefaultInstanceForType() {
        return rcdn.Wikipage.Page.getDefaultInstance();
      }

      public rcdn.Wikipage.Page build() {
        rcdn.Wikipage.Page result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rcdn.Wikipage.Page buildPartial() {
        rcdn.Wikipage.Page result = new rcdn.Wikipage.Page(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pageId_ = pageId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.revisionId_ = revisionId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.summary_ = summary_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.html_ = html_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.category_ = category_;
        if (imageBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            image_ = java.util.Collections.unmodifiableList(image_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.image_ = image_;
        } else {
          result.image_ = imageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rcdn.Wikipage.Page) {
          return mergeFrom((rcdn.Wikipage.Page)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rcdn.Wikipage.Page other) {
        if (other == rcdn.Wikipage.Page.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000004;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasPageId()) {
          setPageId(other.getPageId());
        }
        if (other.hasRevisionId()) {
          setRevisionId(other.getRevisionId());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000020;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasSummary()) {
          bitField0_ |= 0x00000040;
          summary_ = other.summary_;
          onChanged();
        }
        if (other.hasHtml()) {
          bitField0_ |= 0x00000080;
          html_ = other.html_;
          onChanged();
        }
        if (other.hasCategory()) {
          bitField0_ |= 0x00000100;
          category_ = other.category_;
          onChanged();
        }
        if (imageBuilder_ == null) {
          if (!other.image_.isEmpty()) {
            if (image_.isEmpty()) {
              image_ = other.image_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureImageIsMutable();
              image_.addAll(other.image_);
            }
            onChanged();
          }
        } else {
          if (!other.image_.isEmpty()) {
            if (imageBuilder_.isEmpty()) {
              imageBuilder_.dispose();
              imageBuilder_ = null;
              image_ = other.image_;
              bitField0_ = (bitField0_ & ~0x00000200);
              imageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getImageFieldBuilder() : null;
            } else {
              imageBuilder_.addAllMessages(other.image_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasPageId()) {
          
          return false;
        }
        if (!hasRevisionId()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!hasSummary()) {
          
          return false;
        }
        for (int i = 0; i < getImageCount(); i++) {
          if (!getImage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rcdn.Wikipage.Page parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rcdn.Wikipage.Page) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>required string url = 3;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string url = 3;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 3;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 3;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 3;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }

      private int pageId_ ;
      /**
       * <code>required int32 page_id = 4;</code>
       */
      public boolean hasPageId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 page_id = 4;</code>
       */
      public int getPageId() {
        return pageId_;
      }
      /**
       * <code>required int32 page_id = 4;</code>
       */
      public Builder setPageId(int value) {
        bitField0_ |= 0x00000008;
        pageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page_id = 4;</code>
       */
      public Builder clearPageId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pageId_ = 0;
        onChanged();
        return this;
      }

      private int revisionId_ ;
      /**
       * <code>required int32 revision_id = 5;</code>
       */
      public boolean hasRevisionId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 revision_id = 5;</code>
       */
      public int getRevisionId() {
        return revisionId_;
      }
      /**
       * <code>required int32 revision_id = 5;</code>
       */
      public Builder setRevisionId(int value) {
        bitField0_ |= 0x00000010;
        revisionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 revision_id = 5;</code>
       */
      public Builder clearRevisionId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        revisionId_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>required string content = 6;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string content = 6;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string content = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 6;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 6;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 6;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }

      private Object summary_ = "";
      /**
       * <code>required string summary = 7;</code>
       */
      public boolean hasSummary() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string summary = 7;</code>
       */
      public String getSummary() {
        Object ref = summary_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            summary_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string summary = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSummaryBytes() {
        Object ref = summary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          summary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string summary = 7;</code>
       */
      public Builder setSummary(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        summary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string summary = 7;</code>
       */
      public Builder clearSummary() {
        bitField0_ = (bitField0_ & ~0x00000040);
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      /**
       * <code>required string summary = 7;</code>
       */
      public Builder setSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        summary_ = value;
        onChanged();
        return this;
      }

      private Object html_ = "";
      /**
       * <code>optional string html = 8;</code>
       */
      public boolean hasHtml() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string html = 8;</code>
       */
      public String getHtml() {
        Object ref = html_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            html_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string html = 8;</code>
       */
      public com.google.protobuf.ByteString
          getHtmlBytes() {
        Object ref = html_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          html_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string html = 8;</code>
       */
      public Builder setHtml(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        html_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string html = 8;</code>
       */
      public Builder clearHtml() {
        bitField0_ = (bitField0_ & ~0x00000080);
        html_ = getDefaultInstance().getHtml();
        onChanged();
        return this;
      }
      /**
       * <code>optional string html = 8;</code>
       */
      public Builder setHtmlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        html_ = value;
        onChanged();
        return this;
      }

      private Object category_ = "";
      /**
       * <code>optional string category = 9;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string category = 9;</code>
       */
      public String getCategory() {
        Object ref = category_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            category_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string category = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string category = 9;</code>
       */
      public Builder setCategory(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 9;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000100);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 9;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        category_ = value;
        onChanged();
        return this;
      }

      private java.util.List<rcdn.Wikipage.Page.Image> image_ =
        java.util.Collections.emptyList();
      private void ensureImageIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          image_ = new java.util.ArrayList<rcdn.Wikipage.Page.Image>(image_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          rcdn.Wikipage.Page.Image, rcdn.Wikipage.Page.Image.Builder, rcdn.Wikipage.Page.ImageOrBuilder> imageBuilder_;

      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public java.util.List<rcdn.Wikipage.Page.Image> getImageList() {
        if (imageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(image_);
        } else {
          return imageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public int getImageCount() {
        if (imageBuilder_ == null) {
          return image_.size();
        } else {
          return imageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public rcdn.Wikipage.Page.Image getImage(int index) {
        if (imageBuilder_ == null) {
          return image_.get(index);
        } else {
          return imageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder setImage(
          int index, rcdn.Wikipage.Page.Image value) {
        if (imageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIsMutable();
          image_.set(index, value);
          onChanged();
        } else {
          imageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder setImage(
          int index, rcdn.Wikipage.Page.Image.Builder builderForValue) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.set(index, builderForValue.build());
          onChanged();
        } else {
          imageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder addImage(rcdn.Wikipage.Page.Image value) {
        if (imageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIsMutable();
          image_.add(value);
          onChanged();
        } else {
          imageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder addImage(
          int index, rcdn.Wikipage.Page.Image value) {
        if (imageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIsMutable();
          image_.add(index, value);
          onChanged();
        } else {
          imageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder addImage(
          rcdn.Wikipage.Page.Image.Builder builderForValue) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.add(builderForValue.build());
          onChanged();
        } else {
          imageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder addImage(
          int index, rcdn.Wikipage.Page.Image.Builder builderForValue) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.add(index, builderForValue.build());
          onChanged();
        } else {
          imageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder addAllImage(
          Iterable<? extends rcdn.Wikipage.Page.Image> values) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, image_);
          onChanged();
        } else {
          imageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder clearImage() {
        if (imageBuilder_ == null) {
          image_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          imageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public Builder removeImage(int index) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.remove(index);
          onChanged();
        } else {
          imageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public rcdn.Wikipage.Page.Image.Builder getImageBuilder(
          int index) {
        return getImageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public rcdn.Wikipage.Page.ImageOrBuilder getImageOrBuilder(
          int index) {
        if (imageBuilder_ == null) {
          return image_.get(index);  } else {
          return imageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public java.util.List<? extends rcdn.Wikipage.Page.ImageOrBuilder> 
           getImageOrBuilderList() {
        if (imageBuilder_ != null) {
          return imageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(image_);
        }
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public rcdn.Wikipage.Page.Image.Builder addImageBuilder() {
        return getImageFieldBuilder().addBuilder(
            rcdn.Wikipage.Page.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public rcdn.Wikipage.Page.Image.Builder addImageBuilder(
          int index) {
        return getImageFieldBuilder().addBuilder(
            index, rcdn.Wikipage.Page.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .rcdn.Page.Image image = 10;</code>
       */
      public java.util.List<rcdn.Wikipage.Page.Image.Builder> 
           getImageBuilderList() {
        return getImageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rcdn.Wikipage.Page.Image, rcdn.Wikipage.Page.Image.Builder, rcdn.Wikipage.Page.ImageOrBuilder> 
          getImageFieldBuilder() {
        if (imageBuilder_ == null) {
          imageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rcdn.Wikipage.Page.Image, rcdn.Wikipage.Page.Image.Builder, rcdn.Wikipage.Page.ImageOrBuilder>(
                  image_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          image_ = null;
        }
        return imageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:rcdn.Page)
    }

    static {
      defaultInstance = new Page(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rcdn.Page)
  }

  public interface WikiPagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rcdn.WikiPages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    java.util.List<rcdn.Wikipage.Page> 
        getPageList();
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    rcdn.Wikipage.Page getPage(int index);
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    int getPageCount();
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    java.util.List<? extends rcdn.Wikipage.PageOrBuilder> 
        getPageOrBuilderList();
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    rcdn.Wikipage.PageOrBuilder getPageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code rcdn.WikiPages}
   */
  public static final class WikiPages extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rcdn.WikiPages)
      WikiPagesOrBuilder {
    // Use WikiPages.newBuilder() to construct.
    private WikiPages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WikiPages(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WikiPages defaultInstance;
    public static WikiPages getDefaultInstance() {
      return defaultInstance;
    }

    public WikiPages getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WikiPages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                page_ = new java.util.ArrayList<rcdn.Wikipage.Page>();
                mutable_bitField0_ |= 0x00000001;
              }
              page_.add(input.readMessage(rcdn.Wikipage.Page.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          page_ = java.util.Collections.unmodifiableList(page_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rcdn.Wikipage.internal_static_rcdn_WikiPages_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rcdn.Wikipage.internal_static_rcdn_WikiPages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rcdn.Wikipage.WikiPages.class, rcdn.Wikipage.WikiPages.Builder.class);
    }

    public static com.google.protobuf.Parser<WikiPages> PARSER =
        new com.google.protobuf.AbstractParser<WikiPages>() {
      public WikiPages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WikiPages(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<WikiPages> getParserForType() {
      return PARSER;
    }

    public static final int PAGE_FIELD_NUMBER = 1;
    private java.util.List<rcdn.Wikipage.Page> page_;
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    public java.util.List<rcdn.Wikipage.Page> getPageList() {
      return page_;
    }
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    public java.util.List<? extends rcdn.Wikipage.PageOrBuilder> 
        getPageOrBuilderList() {
      return page_;
    }
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    public int getPageCount() {
      return page_.size();
    }
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    public rcdn.Wikipage.Page getPage(int index) {
      return page_.get(index);
    }
    /**
     * <code>repeated .rcdn.Page page = 1;</code>
     */
    public rcdn.Wikipage.PageOrBuilder getPageOrBuilder(
        int index) {
      return page_.get(index);
    }

    private void initFields() {
      page_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPageCount(); i++) {
        if (!getPage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < page_.size(); i++) {
        output.writeMessage(1, page_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < page_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, page_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rcdn.Wikipage.WikiPages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rcdn.Wikipage.WikiPages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rcdn.Wikipage.WikiPages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rcdn.Wikipage.WikiPages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rcdn.Wikipage.WikiPages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rcdn.WikiPages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rcdn.WikiPages)
        rcdn.Wikipage.WikiPagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rcdn.Wikipage.internal_static_rcdn_WikiPages_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rcdn.Wikipage.internal_static_rcdn_WikiPages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rcdn.Wikipage.WikiPages.class, rcdn.Wikipage.WikiPages.Builder.class);
      }

      // Construct using rcdn.Wikipage.WikiPages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pageBuilder_ == null) {
          page_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pageBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rcdn.Wikipage.internal_static_rcdn_WikiPages_descriptor;
      }

      public rcdn.Wikipage.WikiPages getDefaultInstanceForType() {
        return rcdn.Wikipage.WikiPages.getDefaultInstance();
      }

      public rcdn.Wikipage.WikiPages build() {
        rcdn.Wikipage.WikiPages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rcdn.Wikipage.WikiPages buildPartial() {
        rcdn.Wikipage.WikiPages result = new rcdn.Wikipage.WikiPages(this);
        int from_bitField0_ = bitField0_;
        if (pageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            page_ = java.util.Collections.unmodifiableList(page_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.page_ = page_;
        } else {
          result.page_ = pageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rcdn.Wikipage.WikiPages) {
          return mergeFrom((rcdn.Wikipage.WikiPages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rcdn.Wikipage.WikiPages other) {
        if (other == rcdn.Wikipage.WikiPages.getDefaultInstance()) return this;
        if (pageBuilder_ == null) {
          if (!other.page_.isEmpty()) {
            if (page_.isEmpty()) {
              page_ = other.page_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePageIsMutable();
              page_.addAll(other.page_);
            }
            onChanged();
          }
        } else {
          if (!other.page_.isEmpty()) {
            if (pageBuilder_.isEmpty()) {
              pageBuilder_.dispose();
              pageBuilder_ = null;
              page_ = other.page_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPageFieldBuilder() : null;
            } else {
              pageBuilder_.addAllMessages(other.page_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPageCount(); i++) {
          if (!getPage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rcdn.Wikipage.WikiPages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rcdn.Wikipage.WikiPages) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<rcdn.Wikipage.Page> page_ =
        java.util.Collections.emptyList();
      private void ensurePageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          page_ = new java.util.ArrayList<rcdn.Wikipage.Page>(page_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          rcdn.Wikipage.Page, rcdn.Wikipage.Page.Builder, rcdn.Wikipage.PageOrBuilder> pageBuilder_;

      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public java.util.List<rcdn.Wikipage.Page> getPageList() {
        if (pageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(page_);
        } else {
          return pageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public int getPageCount() {
        if (pageBuilder_ == null) {
          return page_.size();
        } else {
          return pageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public rcdn.Wikipage.Page getPage(int index) {
        if (pageBuilder_ == null) {
          return page_.get(index);
        } else {
          return pageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder setPage(
          int index, rcdn.Wikipage.Page value) {
        if (pageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageIsMutable();
          page_.set(index, value);
          onChanged();
        } else {
          pageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder setPage(
          int index, rcdn.Wikipage.Page.Builder builderForValue) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.set(index, builderForValue.build());
          onChanged();
        } else {
          pageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder addPage(rcdn.Wikipage.Page value) {
        if (pageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageIsMutable();
          page_.add(value);
          onChanged();
        } else {
          pageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder addPage(
          int index, rcdn.Wikipage.Page value) {
        if (pageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageIsMutable();
          page_.add(index, value);
          onChanged();
        } else {
          pageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder addPage(
          rcdn.Wikipage.Page.Builder builderForValue) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.add(builderForValue.build());
          onChanged();
        } else {
          pageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder addPage(
          int index, rcdn.Wikipage.Page.Builder builderForValue) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.add(index, builderForValue.build());
          onChanged();
        } else {
          pageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder addAllPage(
          Iterable<? extends rcdn.Wikipage.Page> values) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, page_);
          onChanged();
        } else {
          pageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder clearPage() {
        if (pageBuilder_ == null) {
          page_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public Builder removePage(int index) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.remove(index);
          onChanged();
        } else {
          pageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public rcdn.Wikipage.Page.Builder getPageBuilder(
          int index) {
        return getPageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public rcdn.Wikipage.PageOrBuilder getPageOrBuilder(
          int index) {
        if (pageBuilder_ == null) {
          return page_.get(index);  } else {
          return pageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public java.util.List<? extends rcdn.Wikipage.PageOrBuilder> 
           getPageOrBuilderList() {
        if (pageBuilder_ != null) {
          return pageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(page_);
        }
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public rcdn.Wikipage.Page.Builder addPageBuilder() {
        return getPageFieldBuilder().addBuilder(
            rcdn.Wikipage.Page.getDefaultInstance());
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public rcdn.Wikipage.Page.Builder addPageBuilder(
          int index) {
        return getPageFieldBuilder().addBuilder(
            index, rcdn.Wikipage.Page.getDefaultInstance());
      }
      /**
       * <code>repeated .rcdn.Page page = 1;</code>
       */
      public java.util.List<rcdn.Wikipage.Page.Builder> 
           getPageBuilderList() {
        return getPageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rcdn.Wikipage.Page, rcdn.Wikipage.Page.Builder, rcdn.Wikipage.PageOrBuilder> 
          getPageFieldBuilder() {
        if (pageBuilder_ == null) {
          pageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rcdn.Wikipage.Page, rcdn.Wikipage.Page.Builder, rcdn.Wikipage.PageOrBuilder>(
                  page_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          page_ = null;
        }
        return pageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:rcdn.WikiPages)
    }

    static {
      defaultInstance = new WikiPages(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rcdn.WikiPages)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rcdn_Page_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rcdn_Page_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rcdn_Page_Image_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rcdn_Page_Image_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rcdn_WikiPages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rcdn_WikiPages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016wikipage.proto\022\004rcdn\"\316\001\n\004Page\022\n\n\002id\030\001 " +
      "\002(\005\022\r\n\005title\030\002 \002(\t\022\013\n\003url\030\003 \002(\t\022\017\n\007page_" +
      "id\030\004 \002(\005\022\023\n\013revision_id\030\005 \002(\005\022\017\n\007content" +
      "\030\006 \002(\t\022\017\n\007summary\030\007 \002(\t\022\014\n\004html\030\010 \001(\t\022\020\n" +
      "\010category\030\t \001(\t\022\037\n\005image\030\n \003(\0132\020.rcdn.Pa" +
      "ge.Image\032\025\n\005Image\022\014\n\004link\030\001 \002(\t\"%\n\tWikiP" +
      "ages\022\030\n\004page\030\001 \003(\0132\n.rcdn.Page"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rcdn_Page_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rcdn_Page_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rcdn_Page_descriptor,
        new String[] { "Id", "Title", "Url", "PageId", "RevisionId", "Content", "Summary", "Html", "Category", "Image", });
    internal_static_rcdn_Page_Image_descriptor =
      internal_static_rcdn_Page_descriptor.getNestedTypes().get(0);
    internal_static_rcdn_Page_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rcdn_Page_Image_descriptor,
        new String[] { "Link", });
    internal_static_rcdn_WikiPages_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rcdn_WikiPages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rcdn_WikiPages_descriptor,
        new String[] { "Page", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
